### ISSUE TITLE
Individuare casi d'uso importanti

### ISSUE THREAD

**Issue by samuele-visentin** [RAMtastic6/Project14#14]
Individuare casi d'uso importanti e significativi possibilmente entro 1/12 cosi da poter chiedere feedback sul nostro modo di operare a Imola Informatica e eventualmente al prof. Cardin

**Comment by bassupreme** [comment]
l'incontro con Cardin è stato fatto in data 27/12/2023 ed è stato fornito feedback al gruppo.
