### ISSUE TITLE
Studiare gitflow

### ISSUE THREAD

**Issue by bassupreme** [RAMtastic6/Project14#4]
Questo è il link dove poter studiare come funziona gitflow.
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by samuele-visentin** [comment]
Questo link vi spiega come gestire una feature: http://danielkummer.github.io/git-flow-cheatsheet/

**Comment by bassupreme** [comment]
tutti i membri hanno preso visione del Workflow gitflow.
